### ISSUE TITLE
Packets forwarding to original interface

### ISSUE THREAD

**Issue by bcordix** [udp-redux/udp-broadcast-relay-redux#11]
Running on an Alpine 3.12 x86_64 VM it appears to correctly identify the three interfaces i have connected but when relaying the packets it looks like it is sending it back out the interface it received it from.

`udp-relay:~# ./udp-broadcast-relay-redux --id 10 --port 30050 --dev eth0 --dev eth1 --dev eth2 -d
ID set to 10
Port set to 30050
ID: 10 (ttl: 74), Port 30050
eth0: 2 / 192.168.10.5 / 0.0.0.0
eth1: 3 / 192.168.11.5 / 0.0.0.0
eth2: 4 / 192.168.12.5 / 0.0.0.0
found 3 interfaces total
Done Initializing

<- [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=4 len=28 ttl=64)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=2)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=3)

<- [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=4 len=28 ttl=64)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=2)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=3)

<- [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=4 len=28 ttl=64)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=2)
-> [ 192.168.12.245:30000 -> 192.168.12.255:30050 (iface=3)
`

**Comment by mmorrisontx** [comment]
In `eth0: 2 / 192.168.10.5 / 0.0.0.0`, the final value is supposed to be the broadcast address for the interface, which should probably be `192.168.10.255`. I guess the broadcast address detection is broken somehow with your setup?

https://github.com/udp-redux/udp-broadcast-relay-redux/blob/master/main.c#L264

**Comment by bcordix** [comment]
Not sure what Alpine is doing here. My interfaces file clearly should be setting the broadcast address correctly.


```
udp-relay:~# cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 192.168.10.5
        netmask 255.255.255.0
        broadcast 192.168.10.255
        gateway 192.168.10.1


auto eth1
iface eth1 inet static
        address 192.168.11.5
        netmask 255.255.255.0
        broadcast 192.168.11.255

auto eth2
iface eth2 inet static
        address 192.168.12.5
        netmask 255.255.255.0
        broadcast 192.168.12.255
```

If i manually run ifconfig and set the broadcast address 

```
ifconfig eth0 192.168.10.5 netmask 255.255.255.0 broadcast 192.168.10.255
ifconfig eth1 192.168.11.5 netmask 255.255.255.0 broadcast 192.168.11.255
ifconfig eth2 192.168.12.5 netmask 255.255.255.0 broadcast 192.168.12.255
```

then i do end up seeing the correct behavior.

```
udp-relay:~# ./udp-broadcast-relay-redux --id 10 --port 30050 --dev eth0 --dev eth1 --dev eth
2 -d
ID set to 10
Port set to 30050
ID: 10 (ttl: 74), Port 30050
eth0: 2 / 192.168.10.5 / 192.168.10.255
eth1: 3 / 192.168.11.5 / 192.168.11.255
eth2: 4 / 192.168.12.5 / 192.168.12.255
found 3 interfaces total
Done Initializing

<- [ 192.168.11.64:30000 -> 255.255.255.255:30050 (iface=3 len=28 ttl=64)
-> [ 192.168.11.64:30000 -> 192.168.10.255:30050 (iface=2)
-> [ 192.168.11.64:30000 -> 192.168.12.255:30050 (iface=4)

<- [ 192.168.11.64:30000 -> 192.168.10.255:30050 (iface=2 len=28 ttl=74)
Echo (Ignored)

<- [ 192.168.11.64:30000 -> 192.168.12.255:30050 (iface=4 len=28 ttl=74)
Echo (Ignored)

<- [ 192.168.10.233:30000 -> 192.168.10.255:30050 (iface=2 len=28 ttl=64)
-> [ 192.168.10.233:30000 -> 192.168.11.255:30050 (iface=3)
-> [ 192.168.10.233:30000 -> 192.168.12.255:30050 (iface=4)
```

I will troubleshoot Alpine and try to figure out why/where broadcast address is breaking.

Thank for the reply!

**Comment by bcordix** [comment]
On the Alpine 3.12 x86_64 instance i am working on, it will show the correct broadcast address when the interfaces obtain IPs from DHCP but not when statically set.  I used the 'post-up' statements in my interfaces file to set the broadcast addresses. This survives across reboots and allows for a lean alpine based VM to run this.
 
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 192.168.10.5
        netmask 255.255.255.0
        gateway 192.168.10.1
        post-up ifconfig eth0 192.168.10.5 netmask 255.255.255.0 broadcast 192.168.10.255


auto eth1
iface eth1 inet static
        address 192.168.11.5
        netmask 255.255.255.0
        post-up ifconfig eth1 192.168.11.5 netmask 255.255.255.0 broadcast 192.168.11.255


auto eth2
iface eth2 inet static
        address 192.168.12.5
        netmask 255.255.255.0
        post-up ifconfig eth2 192.168.12.5 netmask 255.255.255.0 broadcast 192.168.12.255
```
