### ISSUE TITLE
Not working in pfsense 21.02

### ISSUE THREAD

**Issue by riess82** [udp-redux/udp-broadcast-relay-redux#14]
export: -broadcast-relay_env: bad variable name

Would be great if anyone could figure this out.

**Comment by ajkavanagh** [comment]
I'm guessing it's the '-' (hyphen, minus-sign) in the variable name.  Try changing it to an underscore.

**Comment by riess82** [comment]
Yes, underscores worked.

The variable is in the usage notes for pfsense 2.4 shell script https://github.com/udp-redux/udp-broadcast-relay-redux/blob/master/usage-notes/pfsense-config/README.md
the "name" variable has the hyphens in use.

Most correct would be to make new usage notes for the new pfsense version, but the easiest way would be to just change the script variable to underscores. Won't hurt in 2.4 (which is way outdated by now).
