### ISSUE TITLE
Doesn't work with VLAN ? -> Yes, it do

### ISSUE THREAD

**Issue by mneitsabes** [udp-redux/udp-broadcast-relay-redux#8]
Hi,

I try to use your program on my pfSense to relay UDP brodcasted message from two networks.

My pfSense is connected to a switch with a LAG. I have VLAN on this LAG so my interfaces are : 

- lagg0 (untagged)
- lagg0.10 (clients)
- lagg0.201 (domotica)

The software used to control the domotica, which is running on the VLAN 10, is broadcasting a single byte in a UDP packet on the port 10000. So I tried this one : 

<pre>$ ./udp-broadcast-relay -d --id 1 --port 10000 --dev lagg0.10 --dev lagg0.201
ID set to 1
Port set to 1
ID: 1 (ttl: 65), Port 100
lagg0.10: 11 / 10.37.10.1 / 10.37.10.255
lagg0.201: 17 / 10.37.201.1 / 10.37.201.255
found 2 interfaces total
Done Initializing
</pre>

(Note that "Port set to 1" is a error in the code. The variable 'id' is used instead of 'port')

But it doesn't work. I see the broadcasted packet with `tcpdump` on the `lagg0.10` but nothing is relayed. I edit your code to add a "print" after receiving a packet (line 434) and I saw that nothing was captured. Then I tried on the untagged interface like that : 

`./udp-broadcast-relay -d --id 1 --port 10000 --dev lagg0 --dev lagg0.201`

and using hping3 to simulate the packet and I see the packet captured but nothing is relayed. 

It seems that the code doesn't work with VLAN but silently fails.

Best regards,

**Comment by sonicsnes** [comment]
It definitely works with vlans -- that's how I use it at home 😄

What's the destination ip of your broadcast packets? Is it multicast?

**Comment by mneitsabes** [comment]
By reading the code, I just unsterstood that "--dev" is just to give the interface for the relay and that the port is binded for all interfaces. So in my case, I must only run : 

`./udp-broadcast-relay -d --id 1 --port 10000 --dev lagg0.201`

While using the software from any VLAN. Is it correct ? 

The destination of the packet is 10.37.10.255. It's simple broadcast. Here is a tcpdump print : 

<pre>[2.4.5-RELEASE][admin@pfSense]/root: tcpdump -i lagg0.10 "port 10000" -vv
tcpdump: listening on lagg0.10, link-type EN10MB (Ethernet), capture size 262144 bytes
12:07:17.367108 IP (tos 0x0, ttl 64, id 56425, offset 0, flags [none], proto UDP (17), length 28)
    10.37.10.35.2438 > 10.37.254.255.10000: [udp sum ok] UDP, length 0
12:07:18.367271 IP (tos 0x0, ttl 64, id 38344, offset 0, flags [none], proto UDP (17), length 28)
    10.37.10.35.2439 > 10.37.254.255.10000: [udp sum ok] UDP, length 0</pre>

**Comment by mneitsabes** [comment]
By reading the code, I just unsterstood that "--dev" is just to give the interface for the relay and that the port is binded for all interfaces. So in my case, I must only run : 

`./udp-broadcast-relay -d --id 1 --port 10000 --dev lagg0.201`

While using the software from any VLAN. Is it correct ? 

The destination of the packet is 10.37.10.255. It's simple broadcast. Here is a tcpdump print : 

<pre>[2.4.5-RELEASE][admin@pfSense.local.lan]/root: tcpdump -i lagg0.10 "port 10000" -vv
tcpdump: listening on lagg0.10, link-type EN10MB (Ethernet), capture size 262144 bytes
12:09:28.739544 IP (tos 0x0, ttl 128, id 19683, offset 0, flags [none], proto UDP (17), length 29)
    10.37.10.29.60123 > 10.37.10.255.10000: [udp sum ok] UDP, length 1</pre>

**Comment by mmorrisontx** [comment]
Hmm, that should be fine... Your command in the first comment is correct, the relay service listens on all interfaces for annoying freebsd reasons, but will only relay packets to and from the interfaces listed with --dev.

It is a bit suspicious that it's printing `Port 100` though ... is that output accurate?

**Comment by mneitsabes** [comment]
> It is a bit suspicious that it's printing `Port 100` though ... is that output accurate?

Sorry, it seems that was an error :

<pre>[2.4.5-RELEASE][admin@pfSense.local.lan]/root: ./udp-broadcast-relay-redux -d --id 1 --port 10000 --dev lagg0.201
ID set to 1
Port set to 10000
ID: 1 (ttl: 65), Port 10000
lagg0.201: 17 / 10.37.201.1 / 10.37.201.255
Found 1 interfaces total
Done Initializing</pre>

The port is listen : 

<pre>[2.4.5-RELEASE][admin@pfSense.local.lan]/root: sockstat | grep udp-broad
root     udp-broadc 96700 3  udp4   *:10000               *:*</pre>
